import { spacing } from "./spacing";
import { radius, motion, shadow, iconography } from "./motion";
import { fonts, typeStyles } from "./typography";
import type { CommerceTokens, ComponentTokens, SemanticTokens, ThemeColors } from "./types";

export const primitiveTokens = {
	colors: {
		orbit: "#050B12",
		orbitDark: "#FCFBFA",
		sukiDot: "#FF5A4A",
		devGray: "#8A93A3",
		offWhite: "#FCFBFA",
		interactive: "#3E63FF",
		neutral50: "#F6F7F9",
		neutral200: "#E7E8EC",
		neutral500: "#667085",
		neutral700: "#344054",
	},
	spacing,
	radius,
	motion,
	shadow,
	iconography,
	typeStyles,
	fonts,
} as const;

export const osukiLightColors: ThemeColors = {
	background: "#FCFBFA",
	surface: "#FFFFFF",
	surfaceRaised: "#F6F7F9",
	border: "#E7E8EC",
	borderStrong: "#C9CED8",
	text: "#050B12",
	textMuted: "#667085",
	textSubtle: "#8A93A3",
	textDisabled: "#B6BDC8",
	primary: "#FF5A4A",
	onPrimary: "#FCFBFA",
	primarySubtle: "rgba(255, 90, 74, 0.14)",
	danger: "#D92D20",
	dangerSubtle: "rgba(217, 45, 32, 0.12)",
	success: "#12B76A",
	warning: "#F79009",
	info: "#3E63FF",
};

export const osukiDarkColors: ThemeColors = {
	background: "#050B12",
	surface: "#101821",
	surfaceRaised: "#172231",
	border: "#263244",
	borderStrong: "#3D485A",
	text: "#FCFBFA",
	textMuted: "#D2D7E0",
	textSubtle: "#A6AFBE",
	textDisabled: "#7F899A",
	primary: "#FF5A4A",
	onPrimary: "#050B12",
	primarySubtle: "rgba(255, 90, 74, 0.24)",
	danger: "#F97066",
	dangerSubtle: "rgba(249, 112, 102, 0.16)",
	success: "#32D583",
	warning: "#FDB022",
	info: "#3E63FF",
};

export const semanticTokens: SemanticTokens = {
	canvas: "background",
	surface: "surface",
	surfaceElevated: "surfaceRaised",
	divider: "border",
	focusRing: "primary",
	interactive: "primary",
	interactiveMuted: "primarySubtle",
	positive: "success",
	caution: "warning",
	critical: "danger",
};

export const commerceTokens: CommerceTokens = {
	price: "text",
	compareAtPrice: "textDisabled",
	sale: "danger",
	saleSubtle: "dangerSubtle",
	inventoryInStock: "success",
	inventoryLow: "warning",
	inventoryOut: "textDisabled",
	checkoutAccent: "primary",
	productCardRadius: "lg",
	productImageRadius: "md",
	productImageAspectRatio: 1,
	productGridMinWidth: 156,
};

export const componentTokens: ComponentTokens = {
	Button: {
		height: 44,
		paddingX: "lg",
		paddingY: "sm",
		radius: "pill",
		primary: { background: "primary", foreground: "onPrimary" },
		secondary: { background: "surface", foreground: "text" },
		ghost: { background: "transparent", foreground: "textMuted" },
		destructive: { background: "dangerSubtle", foreground: "danger" },
	},
	Card: {
		default: { background: "surface" },
		raised: { background: "surface" },
		flat: { background: "surface" },
		radius: { none: "none", xs: "xs", sm: "sm", md: "md", lg: "lg" },
		padding: { none: 0, xs: "xs", sm: "sm", md: "md", lg: "lg" },
	},
	Input: {
		background: "surfaceRaised",
		foreground: "text",
		placeholder: "textDisabled",
		border: "borderStrong",
		borderFocused: "text",
		borderError: "danger",
		radius: "lg",
		paddingX: "md",
		paddingY: "sm",
	},
	Surface: {
		page: "background",
		surface: "surface",
		raised: "surfaceRaised",
	},
	Text: {
		defaultColor: "text",
		displayColor: "text",
		mutedColor: "textMuted",
	},
	Sheet: {
		background: "surface",
		scrim: "rgba(5, 11, 18, 0.48)",
		handle: "borderStrong",
		radius: "lg",
		paddingX: "lg",
		paddingTop: "md",
		paddingBottom: "md",
		maxHeightOffset: "2xl",
	},
	ListItem: {
		minHeight: 52,
		paddingX: "md",
		paddingY: "sm",
		radius: "md",
		background: "transparent",
		selectedBackground: "primarySubtle",
		destructiveBackground: "dangerSubtle",
		gap: "md",
	},
	Tabs: {
		height: 44,
		padding: "xs",
		radius: "pill",
		background: "surfaceRaised",
		activeBackground: "surface",
		activeForeground: "primary",
		inactiveForeground: "textMuted",
	},
};
